// Auth
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const GET_USER_WALLETS = "GET_USER_WALLETS";
export const LOAD_USER = "LOAD_USER";

// Transaction
export const GET_TRANSACTIONS_START = "GET_TRANSACTIONS_START";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAIL = "GET_TRANSACTIONS_FAIL";

export const ADD_TRANSACTION_START = "ADD_TRANSACTION_START";
export const ADD_TRANSACTION_SUCCESS = "ADD_TRANSACTION_SUCCESS";
export const ADD_TRANSACTION_FAIL = "ADD_TRANSACTION_FAIL";

export const RETRIEVE_TRANSACTION_START = "RETRIEVE_TRANSACTION_START";
export const RETRIEVE_TRANSACTION_SUCCESS = "RETRIEVE_TRANSACTION_SUCCESS";
export const RETRIEVE_TRANSACTION_FAIL = "RETRIEVE_TRANSACTION_FAIL";
